listen_addresses = '*'
port = 5432

password_encryption = 'scram-sha-256'
max_connections = 100

shared_buffers = '256MB'
effective_cache_size = '768MB'
maintenance_work_mem = '64MB'
checkpoint_completion_target = 0.9
wal_compression = on

timezone = 'Asia/Ho_Chi_Minh'

log_destination = 'stderr'
logging_collector = off
log_connections = on
log_disconnections = on
log_min_duration_statement = 500

hba_file = '/etc/postgresql/pg_hba.conf'
