listeners.tcp.default = 5672
management.tcp.port = 15672
prometheus.tcp.port = 15692

heartbeat = 60
channel_max = 2048
vm_memory_high_watermark.relative = 0.6
disk_free_limit.absolute = 2GB
consumer_timeout = 1800000
deprecated_features.permit.transient_nonexcl_queues = true

log.console = true
log.console.level = info
